# Generated by Django 2.0.5 on 2019-01-16 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ina_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ina_api.Project'),
        ),
    ]
