# Generated by Django 2.0.5 on 2019-01-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ina_api', '0002_auto_20190128_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.IntegerField(choices=[(1, 'Chat'), (0, 'Project')]),
        ),
    ]
