# Generated by Django 2.0.5 on 2019-01-16 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ina_api', '0002_auto_20190116_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=3000)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ina_api.User')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ina_api.Project')),
            ],
        ),
    ]
