# Generated by Django 2.0.5 on 2018-12-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ina_api', '0002_auto_20181128_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passwordVerification',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
