# Generated by Django 2.0.5 on 2019-01-16 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ina_api', '0003_project_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='project',
        ),
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
