# Generated by Django 2.0.5 on 2019-01-30 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ina_api', '0002_auto_20190121_1348'),
        ('ina_api', '0003_auto_20190128_1615'),
    ]

    operations = [
    ]
