# Generated by Django 2.0.5 on 2019-01-30 14:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ina_api', '0004_merge_20190130_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_followed',
            name='canNotificate',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 30, 14, 59, 4, 570396, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 30, 14, 59, 4, 564395, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 30, 14, 59, 4, 571398, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.IntegerField(choices=[(1, 'Project'), (0, 'Chat')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 30, 14, 59, 4, 564880, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project_update',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 30, 14, 59, 4, 567889, tzinfo=utc)),
        ),
    ]
