# Generated by Django 2.0.5 on 2018-12-20 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ina_api', '0004_chat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='chatUid',
            new_name='chat_uid',
        ),
    ]
