# Generated by Django 2.0.5 on 2019-01-31 10:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ina_api', '0005_auto_20190130_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 31, 10, 29, 35, 344717, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 31, 10, 29, 35, 329214, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 31, 10, 29, 35, 346304, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 31, 10, 29, 35, 330229, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project_update',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 31, 10, 29, 35, 335546, tzinfo=utc)),
        ),
    ]
