# Generated by Django 2.1.3 on 2018-12-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ina_api', '0006_remove_user_passwordverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passwordVerification',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
