# Generated by Django 2.0.5 on 2019-01-31 10:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ina_api', '0006_auto_20190131_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 31, 10, 30, 28, 140314, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 31, 10, 30, 28, 126508, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 31, 10, 30, 28, 141864, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.IntegerField(choices=[(0, 'Chat'), (1, 'Project')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 31, 10, 30, 28, 127498, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project_update',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 31, 10, 30, 28, 132893, tzinfo=utc)),
        ),
    ]
