# Generated by Django 2.0.5 on 2018-12-21 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ina_api', '0003_user_passwordverification'),
        ('ina_api', '0005_auto_20181220_1126'),
    ]

    operations = [
    ]
