# Generated by Django 2.0.5 on 2019-01-09 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ina_api', '0008_merge_20181221_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='creator',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, to='ina_api.User'),
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.CharField(default='no path', max_length=1000),
        ),
    ]
