# Generated by Django 2.0.5 on 2019-01-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ina_api', '0009_auto_20190109_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='picture',
            field=models.CharField(default='leeg', max_length=1000),
            preserve_default=False,
        ),
    ]
