# Generated by Django 2.0.5 on 2019-01-11 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ina_api', '0010_tag_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='picture',
            new_name='thumbnail',
        ),
    ]
